language: cpp

compiler:
  - gcc

sudo: required
dist: trusty


before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55*

script:
  - source /opt/qt55/bin/qt55-env.sh
  - cd CPPWebFramework
  - /opt/qt55/bin/qmake CPPWebFramework.pro
  - make
