language: cpp

compiler:
  - gcc

sudo: required
dist: trusty


before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55*

script:
  - source /opt/qt55/bin/qt55-env.sh
  - cd CPPWebFramework
  - /opt/qt55/bin/qmake CPPWebFramework.pro
  - make

  - cd ..
  - cd examples/HelloWorld
  - /opt/qt55/bin/qmake HelloWorld.pro
  - make

  - cd ..
  - cd ShowFile
  - /opt/qt55/bin/qmake ShowFile.pro
  - make

  - cd ..
  - cd SaveFiles
  - /opt/qt55/bin/qmake SaveFiles.pro
  - make

  - cd ..
  - cd Sessions
  - /opt/qt55/bin/qmake Sessions.pro
  - make

  - cd ..
  - cd Filters
  - /opt/qt55/bin/qmake Filters.pro
  - make

  - cd ..
  - cd CSTLOutExample
  - /opt/qt55/bin/qmake CSTLOutExample.pro
  - make

  - cd ..
  - cd CSTLForExample
  - /opt/qt55/bin/qmake CSTLForExample.pro
  - make

  - cd ..
  - cd CSTLIfExample
  - /opt/qt55/bin/qmake CSTLIfExample.pro
  - make
